/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XnZlIpCFcIz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Crimson_Text } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Aboutus() {
  return (
    (<div className="flex flex-col">
      <section className="w-full py-24 md:py-32 lg:py-40 bg-[#ffe0b2]">
        <div className="container grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
          <div className="space-y-4">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight">
              Timeless Elegance, Crafted with Care
            </h1>
            <p className="text-[#757575] dark:text-[#bdbdbd] text-lg md:text-xl">
              For over a century, our luxury handbag brand has been synonymous with uncompromising quality, exquisite
              design, and a commitment to timeless elegance. Discover the story behind our meticulously crafted pieces.
            </p>
          </div>
          <img
            alt="Luxury Handbag"
            className="rounded-xl object-cover"
            height={600}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/600",
              objectFit: "cover",
            }}
            width={800} />
        </div>
      </section>
      <section className="w-full py-24 md:py-32 lg:py-40 bg-[#fce4ec] dark:bg-[#424242]">
        <div className="container grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
          <div className="order-2 md:order-1">
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight">Unparalleled Craftsmanship</h2>
            <p className="text-[#757575] dark:text-[#bdbdbd] text-lg md:text-xl mt-4">
              Our skilled artisans meticulously handcraft each piece, drawing on centuries-old techniques to ensure the
              highest level of quality and attention to detail. From the selection of the finest leathers to the
              intricate stitching, every step of the process is carried out with the utmost care and precision.
            </p>
          </div>
          <img
            alt="Craftsmanship"
            className="rounded-xl object-cover"
            height={600}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/600",
              objectFit: "cover",
            }}
            width={800} />
        </div>
      </section>
      <section className="w-full py-24 md:py-32 lg:py-40 bg-[#ffe0b2]">
        <div className="container grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
          <img
            alt="Materials"
            className="rounded-xl object-cover"
            height={600}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/600",
              objectFit: "cover",
            }}
            width={800} />
          <div>
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight">Exceptional Materials</h2>
            <p className="text-[#757575] dark:text-[#bdbdbd] text-lg md:text-xl mt-4">
              We source the finest, most luxurious materials from around the world, including the softest Italian
              leathers, the most durable and supple fabrics, and the most exquisite hardware. Each component is
              carefully selected to ensure the longevity and timeless beauty of our handbags.
            </p>
          </div>
        </div>
      </section>
      <section className="w-full py-24 md:py-32 lg:py-40 bg-[#fce4ec] dark:bg-[#424242]">
        <div className="container grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
          <div className="order-2 md:order-1">
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight">Timeless Design Philosophy</h2>
            <p className="text-[#757575] dark:text-[#bdbdbd] text-lg md:text-xl mt-4">
              Our design philosophy is rooted in the pursuit of timeless elegance and enduring style. Each handbag is
              meticulously crafted to be a lasting investment, blending classic silhouettes with modern refinements to
              create pieces that will transcend trends and stand the test of time.
            </p>
          </div>
          <img
            alt="Design Philosophy"
            className="rounded-xl object-cover"
            height={600}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/600",
              objectFit: "cover",
            }}
            width={800} />
        </div>
      </section>
    </div>)
  );
}
