/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VMI9kGK68TT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"

export function Collection() {
  return (
    (<div>
      <section className="w-full h-[500px] relative overflow-hidden">
        <img
          src="/bag16.png"
          alt="Luxe Handbag Collection"
          width={1920}
          height={1080}
          className="w-full h-full object-cover" />
        <div
          className="absolute inset-0 bg-gradient-to-t from-[#f4c4f3]/50 to-transparent" />
        <div
          className="absolute inset-0 flex flex-col items-center justify-center text-center text-white px-4">
          <h1 className="text-4xl md:text-6xl font-bold mb-4">Luxe Handbag Collection</h1>
          <p className="text-lg md:text-xl max-w-[600px] mb-8 text-orange-500 dark:text-orange-400 font-bold">
          Carry Confidence, Crafted with Care
          </p>          
        </div>
      </section>
      <section className="py-12 md:py-16">
        <div className="container grid grid-cols-1 md:grid-cols-[200px_1fr] gap-8">
        <div className="space-y-4">
            <h3 className="text-lg font-semibold">Filters</h3>
            <div className="space-y-2">
              <Label htmlFor="price-filter">Price</Label>
              <Select id="price-filter" defaultValue="all" className="bg-orange-500 text-white">
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="All Prices" />
                </SelectTrigger>
                <SelectContent className="bg-orange-500 text-white">
                  <SelectItem value="all">All Prices</SelectItem>
                  <SelectItem value="under-100">Under ₹1000</SelectItem>
                  <SelectItem value="100-300">₹1000 - ₹3000</SelectItem>
                  <SelectItem value="300-500">₹3000 - ₹5000</SelectItem>
                  <SelectItem value="over-500">Over ₹5000</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="color-filter">Color</Label>
              <Select id="color-filter" defaultValue="all" className="bg-orange-500 text-white">
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="All Colors" />
                </SelectTrigger>
                <SelectContent className="bg-orange-500 text-white">
                  <SelectItem value="all">All Colors</SelectItem>
                  <SelectItem value="black">Black</SelectItem>
                  <SelectItem value="brown">Brown</SelectItem>
                  <SelectItem value="tan">Tan</SelectItem>
                  <SelectItem value="white">White</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="style-filter">Style</Label>
              <Select id="style-filter" defaultValue="all" className="bg-orange-500 text-white">
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="All Styles" />
                </SelectTrigger>
                <SelectContent className="bg-orange-500 text-white">
                  <SelectItem value="all">All Styles</SelectItem>
                  <SelectItem value="tote">Tote</SelectItem>
                  <SelectItem value="satchel">Satchel</SelectItem>
                  <SelectItem value="crossbody">Crossbody</SelectItem>
                  <SelectItem value="clutch">Clutch</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div
            className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <div
              className="bg-white dark:bg-orange-500 rounded-lg shadow-lg overflow-hidden">
              <img
                src="/bag17.png"
                alt="Luxe Handbag"
                width={400}
                height={400}
                className="w-full h-64 object-cover" />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Luxe Leather Tote</h3>
                <p className="text-gray-500 dark:text-white">₹2299</p>
                <Button size="sm" className="bg-orange-500 hover:bg-orange-600 text-white">
                  Add to Cart
                </Button>
              </div>
            </div>
            <div
              className="bg-white dark:bg-orange-500 rounded-lg shadow-lg overflow-hidden">
              <img
                src="/bag26.png"
                alt="Luxe Handbag"
                width={400}
                height={400}
                className="w-full h-64 object-cover" />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Elegant Satchel</h3>
                <p className="text-gray-500 dark:text-white">₹1399</p>
                <Button size="sm" className="bg-orange-500 hover:bg-orange-600 text-white">
                  Add to Cart
                </Button>
              </div>
            </div>
            <div
              className="bg-white dark:bg-orange-500 rounded-lg shadow-lg overflow-hidden">
              <img
                src="/bag27.png"
                alt="Luxe Handbag"
                width={400}
                height={400}
                className="w-full h-64 object-cover" />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Chic Crossbody</h3>
                <p className="text-gray-500 dark:text-white">₹3599</p>
                <Button size="sm" className="bg-orange-500 hover:bg-orange-600 text-white">
                  Add to Cart
                </Button>
              </div>
            </div>
            <div
              className="bg-white dark:bg-orange-500 rounded-lg shadow-lg overflow-hidden">
              <img
                src="/bag25.png"
                alt="Luxe Handbag"
                width={400}
                height={400}
                className="w-full h-64 object-cover" />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Minimalist Clutch</h3>
                <p className="text-gray-500 dark:text-white">₹1599</p>
                <Button size="sm" className="bg-orange-500 hover:bg-orange-600 text-white">
                  Add to Cart
                </Button>
              </div>
            </div>
            <div
              className="bg-white dark:bg-orange-500 rounded-lg shadow-lg overflow-hidden">
              <img
                src="/bag28.png"
                alt="Luxe Handbag"
                width={400}
                height={400}
                className="w-full h-64 object-cover" />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold"> Backpack</h3>
                <p className="text-gray-500 dark:text-white">₹4399</p>
                <Button size="sm" className="bg-orange-500 hover:bg-orange-600 text-white">
                  Add to Cart
                </Button>
              </div>
            </div>
            <div
              className="bg-white dark:bg-orange-500 rounded-lg shadow-lg overflow-hidden">
              <img
                src="/bag29.png"
                alt="Luxe Handbag"
                width={400}
                height={400}
                className="w-full h-64 object-cover" />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Hobo Bag</h3>
                <p className="text-gray-500 dark:text-white">₹2349</p>
                <Button size="sm" className="bg-orange-500 hover:bg-orange-600 text-white">
                  Add to Cart
                </Button>
              </div>
            </div>
            <div
              className="bg-white dark:bg-orange-500 rounded-lg shadow-lg overflow-hidden">
              <img
                src="/bag30.png"
                alt="Luxe Handbag"
                width={400}
                height={400}
                className="w-full h-64 object-cover" />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Sleek Bucket Bag</h3>
                <p className="text-gray-500 dark:text-white">₹1279</p>
                <Button size="sm" className="bg-orange-500 hover:bg-orange-600 text-white">
                  Add to Cart
                </Button>
              </div>
            </div>
            <div
              className="bg-white dark:bg-orange-500 rounded-lg shadow-lg overflow-hidden">
              <img
                src="/bag31.png"
                alt="Luxe Handbag"
                width={400}
                height={400}
                className="w-full h-64 object-cover" />
              <div className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Timeless Shoulder Bag</h3>
                <p className="text-gray-500 dark:text-white">₹2399</p>
                <Button size="sm" className="bg-orange-500 hover:bg-orange-600 text-white">
                  Add to Cart
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>)
  );
}
