/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rzQs0hGEf63
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Login() {
  return (
    (<div
      className="flex h-screen items-center justify-center bg-[#f0f0f0] dark:bg-[#2c2c2c]">
      <div
        className="mx-4 w-full max-w-md rounded-lg bg-white p-6 shadow-lg dark:bg-[#3c3c3c] sm:p-8">
        <div className="space-y-4">
          <div className="text-center">
            <h1
              className="text-3xl font-bold tracking-tight text-[#4a4a4a] dark:text-[#e0e0e0] sm:text-4xl">
              Welcome to Luxe Handbags
            </h1>
            <p className="mt-2 text-[#7a7a7a] dark:text-[#b0b0b0]">Sign in to your account or create a new one.</p>
          </div>
          <form className="space-y-4">
            <div>
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="name@example.com" required type="email" />
            </div>
            <div>
              <Label htmlFor="password">Password</Label>
              <Input id="password" placeholder="••••••••" required type="password" />
            </div>
              <Button className="w-full bg-[#ff8c00] hover:bg-[#ff7b00] text-[#f0f0f0] dark:bg-[#ff69b4] dark:hover:bg-[#ff58a4] dark:text-[#2c2c2c]"
              type="submit">
                Sign in
              </Button>
            
            <div className="text-center text-sm text-[#7a7a7a] dark:text-[#b0b0b0]">
              Don't have an account?
              <Link className="font-medium text-[#ff8c00] hover:underline dark:text-[#ff69b4]" href="/login/signup">
                Sign up
              </Link>
            </div>
          </form>
        </div>
      </div>
    </div>)
  );
}
