/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MPcf59JLRDG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Newarrival() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <HandIcon className="h-6 w-6 text-pink-500" />
          <span className="sr-only">Luxe Handbags</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 text-orange-500"
            href="/collection">
            Shop
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 text-orange-500"
            href="/aboutus">
            About Us
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-pink-100">
          <div className="container px-4 md:px-6">
            <div
              className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <img
                alt="Latest Handbag Collection"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
                height="550"
                src="/bag9.png"
                width="550" />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1
                    className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none text-orange-500">
                    Discover Our Latest Handbag Collection
                  </h1>
                  <p className="max-w-[600px] text-pink-500 md:text-xl dark:text-pink-400">
                    
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-orange-500 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-orange-600 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-orange-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-orange-400 dark:text-gray-900 dark:hover:bg-orange-400/90 dark:focus-visible:ring-orange-300"
                    href="/collection">
                    Shop Now
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-pink-100">
          <div className="container px-4 md:px-6">
            <div
              className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2
                  className="text-3xl font-bold tracking-tighter sm:text-5xl text-orange-500">
                  Explore Our Newest Handbag Designs
                </h2>
                <p
                  className="max-w-[900px] text-pink-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-pink-400">
                  Discover the latest additions to our luxurious handbag collection, each piece crafted with the utmost
                  care and attention to detail.
                </p>
              </div>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                alt="Handbag 1"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/bag21.png"
                width="550" />
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold text-orange-500">Luxe Leather Tote</h3>
                  <p className="text-pink-500 dark:text-pink-400">
                    Crafted from the finest Italian leather, this timeless tote is the perfect everyday companion.
                  </p>
                  <div className="flex items-center gap-2">
                    <span className="text-lg font-bold text-orange-500">₹1395</span>
                    <Link
                      className="inline-flex h-9 items-center justify-center rounded-md bg-orange-500 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-orange-600 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-orange-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-orange-400 dark:text-gray-900 dark:hover:bg-orange-400/90 dark:focus-visible:ring-orange-300"
                      href="#">
                      Add to Cart
                    </Link>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                alt="Handbag 2"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                height="310"
                src="bag22.png"
                width="550" />
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold text-orange-500">Structured Satchel</h3>
                  <p className="text-pink-500 dark:text-pink-400">
                    This structured satchel in premium pebbled leather is the perfect balance of style and
                    functionality.
                  </p>
                  <div className="flex items-center gap-2">
                    <span className="text-lg font-bold text-orange-500">₹3995</span>
                    <Link
                      className="inline-flex h-9 items-center justify-center rounded-md bg-orange-500 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-orange-600 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-orange-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-orange-400 dark:text-gray-900 dark:hover:bg-orange-400/90 dark:focus-visible:ring-orange-300"
                      href="#">
                      Add to Cart
                    </Link>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <img
                alt="Handbag 3"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/bag23.png"
                width="550" />
              <div className="flex flex-col justify-center space-y-4">
                <div className="grid gap-1">
                  <h3 className="text-xl font-bold text-orange-500">Embellished Clutch</h3>
                  <p className="text-pink-500 dark:text-pink-400">
                    This exquisite clutch features intricate embellishments and a sleek, modern design.
                  </p>
                  <div className="flex items-center gap-2">
                    <span className="text-lg font-bold text-orange-500">₹2099</span>
                    <Link
                      className="inline-flex h-9 items-center justify-center rounded-md bg-orange-500 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-orange-600 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-orange-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-orange-400 dark:text-gray-900 dark:hover:bg-orange-400/90 dark:focus-visible:ring-orange-300"
                      href="#">
                      Add to Cart
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-pink-500 dark:text-pink-400">© 2024 Luxe Handbags. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-xs hover:underline underline-offset-4 text-orange-500"
            href="#">
            Terms of Service
          </Link>
          <Link
            className="text-xs hover:underline underline-offset-4 text-orange-500"
            href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}

function HandIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 11V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v0" />
      <path d="M14 10V4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v2" />
      <path d="M10 10.5V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v8" />
      <path
        d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15" />
    </svg>)
  );
}
