/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/r9jldrd9phy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Signup() {
  return (
    (<div
      className="flex h-screen items-center justify-center bg-gray-100 dark:bg-gray-900">
      <div
        className="mx-4 w-full max-w-md rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800 sm:p-8">
        <div className="space-y-4">
          <div className="text-center">
            <h1
              className="text-3xl font-bold tracking-tight text-orange-600 dark:text-pink-500 sm:text-4xl">
              Create an account
            </h1>
            <p className="mt-2 text-gray-600 dark:text-gray-400">
              Already have an account?
              <Link
                className="font-medium text-orange-600 hover:underline dark:text-pink-500"
                href="/login">
                Sign in
              </Link>
            </p>
          </div>
          <form className="space-y-4">
            <div>
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="John Doe" required type="text" />
            </div>
            <div>
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="name@example.com" required type="email" />
            </div>
            <div>
              <Label htmlFor="password">Password</Label>
              <Input id="password" placeholder="••••••••" required type="password" />
            </div>
            <div>
              <Label htmlFor="confirm-password">Confirm Password</Label>
              <Input id="confirm-password" placeholder="••••••••" required type="password" />
            </div>
            <Link href="/">
            <Button
              className="w-full bg-orange-600 hover:bg-orange-700 dark:bg-pink-500 dark:hover:bg-pink-600"
              type="submit">
              Sign up
            </Button>
            </Link>
          </form>
        </div>
      </div>
    </div>)
  );
}
