/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ELdGB8K1PsB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Thankyou() {
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-br from-[#FFA07A] to-[#FF69B4]">
      <div className="max-w-md p-8 bg-white rounded-lg shadow-md">
        <div className="flex flex-col items-center space-y-4">
          <CircleCheckIcon className="text-[#FFA07A] w-16 h-16" />
          <h1 className="text-3xl font-bold text-[#FF69B4]">Thank you!</h1>
          <p className="text-[#FFA07A] text-center">
            We appreciate your interest in our luxe handbag collection. We'll be in touch soon with more information.
          </p>
          <Link
            href="/"
            className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-[#FFA07A] rounded-md shadow-sm hover:bg-[#FFA07A]/90 focus:outline-none focus:ring-2 focus:ring-[#FFA07A] focus:ring-offset-2"
            prefetch={false}>
            Back to Main Site
          </Link>
        </div>
      </div>
    </div>)
  );
}

function CircleCheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>)
  );
}
